
modLoader="javafml"
loaderVersion="[43,)"
license="MIT"


[[mods]]
modId="creatingspace"
version = "1.7.1.test1"
displayName="Creating Space"
logoFile = "logo.png"
credits='''
Translation :
RealAntEngineer -> English and French
PopCorn -> Russian and Ukrainian
'''
authors="Real Ant Engineer"

description='''
Going to space with create
'''

[[dependencies.creatingspace]]
modId="create"
mandatory=true
versionRange="[0.5.1.a,)"
ordering="NONE"
side="BOTH"
